name: Windows build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        install: >
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
        update: true

    - name: Install SDL2 and SDL2_ttf via Chocolatey
      run: |
        choco install sdl2
        choco install sdl2-ttf

    - name: Configure build with CMake
      run: |
        mkdir build
        cd build
        bash -c 'find /mingw64/share/ -name "SDL2Config.cmake"'
        cmake -G "MinGW Makefiles" -DUSE_SDL2=ON -DWIN_BUILD=ON ..

    - name: Build the project
      run: |
        cd build
        make

    - name: Collect required DLLs
      run: |
        cp /mingw64/bin/SDL2.dll build/
        cp /mingw64/bin/SDL2_ttf.dll build/
        cp /mingw64/bin/libgcc_s_seh-1.dll build/
        cp /mingw64/bin/libstdc++-6.dll build/
        cp /mingw64/bin/libwinpthread-1.dll build/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: |
          build/*.exe
          build/*.dll
